[service.fuzz]
cmd = [
    "cargo",
    "+nightly",
    "fuzz",
    "run",
    "--debug-assertions", # this is default but lets be explicit
    "-j",
    { var = "jobs" },
    { var = "$profile" },
]
# Make fuzz tests run slightly faster
env.RUSTFLAGS = "-C target-cpu=native"
profiles = ["datetime", "parse_compare_toml", "parse_value"]
var.jobs.default = "1"
var.jobs.description = "Number of job processes to spawn during fuzzing."
var.sanitizer.default = "address"

[action.test-coverage]
cmd = ["cargo", "+nightly", "llvm-cov", "-q", "--branch"]

[action.review-snapshots]
managed = false
cmd = ["cargo", "insta", "review", "--workspace"]

[action.build-docs]
cmd = ["cargo", "doc"]

[action.benchmark]
cmd = [
    "cargo",
    "+nightly",
    "run",
    "--release",
    { if.profile = "compile-time", then = [
        "--",
        "compile",
    ] },
]
pwd = "./crates/benchmark"
profiles = ["runtime", "compile-time"]

[action.fmt]
sh = '''
cargo fmt
cargo fmt --manifest-path crates/third-party-integration-tests/Cargo.toml
cargo fmt --manifest-path crates/fuzz/Cargo.toml
cargo fmt --manifest-path crates/benchmark/Cargo.toml
cargo fmt --manifest-path crates/error-examples/Cargo.toml
cargo fmt --manifest-path crates/toml-test-harness/Cargo.toml
cargo fmt --manifest-path crates/stress-tests/Cargo.toml
cargo fmt --manifest-path crates/toml-spanner-macros-source/Cargo.toml
cargo fmt --manifest-path crates/macro-preprocessor/Cargo.toml
'''

[action.build-macros]
pwd = "./crates/macro-preprocessor/"
cmd = [
    "cargo",
    "run",
    "../toml-spanner-macros-source",
    "../toml-spanner-macros",
]
cache.key = [
    { modified = "./crates/macro-preprocessor/" },
    { modified = "./crates/toml-spanner-macros-source/" },
]

[action.macro-main]
pwd = "./crates/toml-spanner-macros-source"
cmd = ["cargo", "run"]


[test.clippy]
cmd = ["cargo", "clippy", "--all-targets", "--", "--deny=warnings"]
tag = ["lint"]

[test.snapshot-tests]
cmd = ["cargo", "insta", "test", "-p", "snapshot-tests"]
tag = ["fast"]

[test.cargo-test]
cmd = ["cargo", "test", "-q"]
require = ["build-macros"]
tag = ["fast"]

[test.miri-stress-tests]
pwd = "crates/stress-tests"
cmd = ["cargo", "+nightly", "miri", "run", "--", "3"]
tag = ["slow", "miri"]

[test.stress-tests]
pwd = "crates/stress-tests"
cmd = ["cargo", "run", "--", "5000"]
tag = ["fast"]

[test.miri-tests]
info = "Requires `cargo-nextest` and miri."
cmd = ["cargo", "+nightly", "miri", "nextest", "run"]
tag = ["slow", "miri"]


[test.miri-tests-32bit]
cmd = [
    "cargo",
    "+nightly",
    "miri",
    "nextest",
    "run",
    "-p",
    "toml-spanner",
    "--lib",
    "--target",
    "i686-unknown-linux-gnu",
]
info = "Requires `cargo-nextest` and miri."
tag = ["slow", "miri"]

[test.official-toml-test-suite]
info = """
Validate toml-spanner against https://github.com/toml-lang/toml-test decoder and encoder test suite
Requires `toml-test` to be installed, see REPO for installation procedure.
"""
tag = ["fast"]
pwd = "crates/toml-test-harness"
sh = '''
DECODER=$(cargo --config "target.'cfg(unix)'.runner = 'echo'" run --bin decoder --release || exit 1)
ENCODER=$(cargo --config "target.'cfg(unix)'.runner = 'echo'" run --bin encoder --release || exit 1)
toml-test test -toml 1.1 "-decoder=$DECODER" "-encoder=$ENCODER"
'''

[test.check-workspace]
cmd = ["cargo", "check", "--workspace", "--all-targets"]
tag = ["fast"]

[test.check-fuzz]
pwd = "crates/fuzz"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-benchmark]
pwd = "crates/benchmark"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-stress-tests]
pwd = "crates/stress-tests"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-toml-test-harness]
pwd = "crates/toml-test-harness"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-error-examples]
pwd = "crates/error-examples"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-third-party-integration-tests]
pwd = "crates/third-party-integration-tests"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-macro-preprocessor]
pwd = "crates/macro-preprocessor"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.check-macros-source]
pwd = "crates/toml-spanner-macros-source"
cmd = ["cargo", "check", "--all-targets"]
tag = ["fast"]

[test.typos]
cmd = "typos"
tag = ["fast"]
