use proc_macro::{Punct, Spacing};
pub static BLIT_SRC: &[u8] =
b"\n\t+#\x06\x08\n\t;\x06\x08\x03\"\x03\x00!S_\t\x07X\n\t\x11\x06\x08\x03\x00W\t\x07\n\tF\x06\x08\x10\x03\n\t(\n\t\'\n\t\x1c\x06Y\x00\n\t\x1b\x03^XO\x02W\r:\x04\x01\x020\n\t2`\x01\x02O\r>\n\tS\r8\x0c\x0b\rE`\x01\x02O\r&\x02O\rD\x02O\r5O\rA`\x04\x01Z\n\tJ\"\n\tJ\x00!H\x06\x08\x07\x08P\x00_\t\x07X\n\t\x12\x06\x08^RX9\n\tI\n\tN\x00_\r\\Q_\rM9\rV\n\tT\n\tU\n\tH\x07P\r\x04\x00_\r\\\x00=^R\n\tJ\n\t*\x00\x1d\x00_\r\\\x00\n\tJ\n\tH=\x0f9\rL`\x03\x03\n\tS_\x00W\x02[\r>\x02[\r&\x02[\rD\x02[\r5]\rV\x00,\x00_\r\\\x00^6\x02W\r\x16\x04\x01G6\x05\x03ZY\n\t<\x05\x03?_\r@\n\tF\n\tCGPQG6\x02W\r\x14`^]\x02W\r\x17\x04\x01^3\x02]\r3`\x01Q?3\r\x18`\x05\x02$\x00/\x02\x073\n\t;\n\tS_\x00/^X[\x02/\r:[\rA`\x04\x01ZG$\r\x19X]\x01]\rV4\x00_]\rL`XB\x01B\rV\x00]\rL`\x00_\r\\\x00B\rL`^X[\x02W\r:\x04\x01^7\t\x07)\x02[\r5G7^1\x02[\r%\x04\x01[\rA`\x04\x01Z_\x001\x04\x01^X[\x021\r:\x15\n\t\x1a <\t`\x02";
pub const IDENT_SIZE: usize = 79;
pub static NAMES: [&str; 79] = [
    "Context",
    "ToContext",
    "allow",
    "as_str",
    "clippy",
    "expect_string",
    "expect_table",
    "len",
    "name",
    "question_mark",
    "Failed",
    "Result",
    "__val",
    "as",
    "automatically_derived",
    "const",
    "fn",
    "for",
    "impl",
    "key",
    "required_item",
    "required_mapped",
    "result",
    "std",
    "str",
    "to_optional_item",
    "toml_spanner",
    "val",
    "where",
    "ref",
    "value",
    "Default",
    "content",
    "default",
    "entries",
    "inner",
    "required",
    "s",
    "tag",
    "unwrap_or_else",
    "__table",
    "table_helper",
    "FromItem",
    "_",
    "if",
    "optional_mapped",
    "Err",
    "error_expected_but_found",
    "expect_empty",
    "outer",
    "string",
    "optional",
    "unwrap_or_default",
    "Item",
    "match",
    "to_item",
    "Table",
    "ToItem",
    "else",
    "into_item",
    "report_error",
    "try_with_capacity",
    "__th",
    "self",
    "return",
    "Some",
    "from_item",
    "Key",
    "anon",
    "insert",
    "__item",
    "mut",
    "Self",
    "Ok",
    "th",
    "arena",
    "table",
    "let",
    "__ctx",
];
pub const PUNCT_SIZE: usize = 17;
pub fn punct_cache_initial_state() -> [Punct; PUNCT_SIZE] {
    [
        Punct::new(',', Spacing::Alone),
        Punct::new(';', Spacing::Alone),
        Punct::new('=', Spacing::Alone),
        Punct::new('>', Spacing::Alone),
        Punct::new('?', Spacing::Alone),
        Punct::new('=', Spacing::Joint),
        Punct::new('<', Spacing::Alone),
        Punct::new('&', Spacing::Alone),
        Punct::new('\'', Spacing::Joint),
        Punct::new(':', Spacing::Alone),
        Punct::new(':', Spacing::Joint),
        Punct::new('|', Spacing::Alone),
        Punct::new('|', Spacing::Joint),
        Punct::new('.', Spacing::Alone),
        Punct::new('#', Spacing::Joint),
        Punct::new('!', Spacing::Alone),
        Punct::new('-', Spacing::Joint),
    ]
}
